import { ChannelInfo } from "@/types/nca";

export const NCA_CHANNELS: ChannelInfo[] = [
  {
    index: 0,
    name: "Red Photopigment (R)",
    role: "Visible light phenotype — red optical emission spectrum",
    category: "Visual",
    colorHint: "#ef4444",
  },
  {
    index: 1,
    name: "Green Photopigment (G)",
    role: "Visible light phenotype — green optical emission spectrum",
    category: "Visual",
    colorHint: "#22c55e",
  },
  {
    index: 2,
    name: "Blue Photopigment (B)",
    role: "Visible light phenotype — blue optical emission spectrum",
    category: "Visual",
    colorHint: "#3b82f6",
  },
  {
    index: 3,
    name: "Cell Viability / Alpha (α)",
    role: "Alive barrier threshold — cells below 0.1 are recycled into stroma",
    category: "Visual",
    colorHint: "#ffffff",
  },
  {
    index: 4,
    name: "Horizontal Polarity (∇X)",
    role: "Lateral biochemical coordinate vector guiding bilateral symmetry",
    category: "Polarity",
    colorHint: "#06b6d4",
  },
  {
    index: 5,
    name: "Vertical Polarity (∇Y)",
    role: "Anterior-Posterior gradient establishing head-to-tail orientation",
    category: "Polarity",
    colorHint: "#ec4899",
  },
  {
    index: 6,
    name: "Turing Activator (A)",
    role: "Short-range auto-catalytic morphogen driving local cell proliferation",
    category: "Morphogen",
    colorHint: "#facc15",
  },
  {
    index: 7,
    name: "Turing Inhibitor (I)",
    role: "Long-range diffuse antagonist preventing uncontrolled tumorous spread",
    category: "Morphogen",
    colorHint: "#a855f7",
  },
  {
    index: 8,
    name: "Mitotic Potential (M)",
    role: "Cell division drive; high at damaged margins to fuel rapid regeneration",
    category: "Cellular Energy",
    colorHint: "#10b981",
  },
  {
    index: 9,
    name: "Homeostatic Anchor (H)",
    role: "Attractor memory vector locking final stable anatomical coordinates",
    category: "Memory",
    colorHint: "#38bdf8",
  },
  {
    index: 10,
    name: "Extracellular Adhesion (E)",
    role: "Membrane tension holding tissue boundaries against entropy",
    category: "Memory",
    colorHint: "#f97316",
  },
  {
    index: 11,
    name: "Bio-Electric Pulse (Ca²⁺)",
    role: "Rapid transmembrane signal transmitting localized trauma across tissue",
    category: "Cellular Energy",
    colorHint: "#e11d48",
  },
  {
    index: 12,
    name: "Ectodermal Marker (Ecto)",
    role: "Outer epidermal differentiation pathway (skin, shell, petal boundary)",
    category: "Morphogen",
    colorHint: "#14b8a6",
  },
  {
    index: 13,
    name: "Mesodermal Marker (Meso)",
    role: "Core structural differentiation (vascular trunk, central organs)",
    category: "Morphogen",
    colorHint: "#8b5cf6",
  },
  {
    index: 14,
    name: "Metabolic Flux (ATP)",
    role: "Cellular respiration rate powering continuous local conv evaluations",
    category: "Cellular Energy",
    colorHint: "#84cc16",
  },
  {
    index: 15,
    name: "Apoptotic Signaling (Apop)",
    role: "Controlled programmed cell death to carve fine limb silhouettes",
    category: "Memory",
    colorHint: "#f43f5e",
  },
];
