"use client";

import React from "react";

interface InfoModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const InfoModal: React.FC<InfoModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fade-in select-none">
      <div className="sh-dark-card relative w-full max-w-2xl max-h-[90vh] overflow-y-auto bg-[#090a10] border border-white/[0.12] rounded-2xl p-6 shadow-[0_25px_60px_rgba(0,0,0,0.8)] flex flex-col gap-5 text-zinc-300 font-sans">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-white/[0.08]">
          <div className="flex items-center gap-2.5">
            <span className="text-2xl">🧫</span>
            <div>
              <h2 className="font-mono text-base sm:text-lg font-bold text-white tracking-wide">
                HOW NEURAL CELLULAR AUTOMATA WORK
              </h2>
              <p className="text-xs text-emerald-400 font-mono">
                Decentralized morphogenesis, self-repair & biological AI
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-white/[0.05] hover:bg-white/[0.1] text-zinc-400 hover:text-white flex items-center justify-center font-mono text-sm transition-all cursor-pointer"
          >
            ✕
          </button>
        </div>

        {/* The Core Concept */}
        <div className="p-3.5 rounded-xl bg-emerald-950/25 border border-emerald-500/25 font-mono text-xs text-emerald-200 leading-relaxed">
          <strong className="text-white">The Big Idea: </strong>
          In standard deep learning, images or assets are generated by a centralized model. In a{" "}
          <strong className="text-emerald-300">Neural Cellular Automaton (NCA)</strong>, there is{" "}
          <strong className="text-white">no centralized controller</strong>. Every single cell runs
          the exact same micro-network, only talks to its 8 immediate neighbors, and the global organism
          emerges autonomously through pure local communication!
        </div>

        {/* Scientific Pillars */}
        <div className="flex flex-col gap-3 font-mono text-xs">
          <span className="text-[10px] text-zinc-400 uppercase tracking-widest font-bold">
            The 4 Biological Pillars
          </span>

          {/* 1. Perception */}
          <div className="p-3 rounded-lg bg-[#0d0e17] border border-white/[0.05] flex items-start gap-3">
            <div className="w-7 h-7 rounded-md bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center shrink-0 text-sm font-bold">
              1
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="text-emerald-300 font-bold text-xs uppercase">
                Perception (Sobel Gradient Filters)
              </span>
              <p className="text-[11px] text-zinc-400 font-sans leading-relaxed">
                Cells do not have eyes or GPS coordinates. They sense their immediate 3×3 neighborhood
                using fixed spatial filters (Identity, horizontal Sobel ∂/∂x, and vertical Sobel ∂/∂y).
                This allows cells to infer local tissue boundaries, polarity, and orientation.
              </p>
            </div>
          </div>

          {/* 2. Hidden Biochemical Channels */}
          <div className="p-3 rounded-lg bg-[#0d0e17] border border-white/[0.05] flex items-start gap-3">
            <div className="w-7 h-7 rounded-md bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 flex items-center justify-center shrink-0 text-sm font-bold">
              2
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="text-cyan-300 font-bold text-xs uppercase">
                16-Dimensional State Vectors
              </span>
              <p className="text-[11px] text-zinc-400 font-sans leading-relaxed">
                Each cell stores 16 continuous numerical channels. Channels 0–3 encode visible RGBA
                pigments. Channels 4–15 operate as invisible morphogen chemicals: Turing activators,
                inhibitors, mitotic division signals, and homeostatic attractor anchors.
              </p>
            </div>
          </div>

          {/* 3. Asynchronous Stochastics */}
          <div className="p-3 rounded-lg bg-[#0d0e17] border border-white/[0.05] flex items-start gap-3">
            <div className="w-7 h-7 rounded-md bg-purple-500/10 border border-purple-500/20 text-purple-400 flex items-center justify-center shrink-0 text-sm font-bold">
              3
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="text-purple-300 font-bold text-xs uppercase">
                Stochastic Asynchronous Updates
              </span>
              <p className="text-[11px] text-zinc-400 font-sans leading-relaxed">
                In biological physics, cells do not tick in unison like a clock. At every step, only a
                random 50% subset of cells update their state. This introduces temporal noise that
                trains the system to be resilient against desynchronization.
              </p>
            </div>
          </div>

          {/* 4. Autonomous Self-Healing */}
          <div className="p-3 rounded-lg bg-[#0d0e17] border border-white/[0.05] flex items-start gap-3">
            <div className="w-7 h-7 rounded-md bg-rose-500/10 border border-rose-500/20 text-rose-400 flex items-center justify-center shrink-0 text-sm font-bold">
              4
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="text-rose-300 font-bold text-xs uppercase">
                Self-Repair & Morphogenetic Attractors
              </span>
              <p className="text-[11px] text-zinc-400 font-sans leading-relaxed">
                When you slice an organism with the laser scalpel, edge cells immediately perceive the
                abrupt drop in neighbor inhibitor levels. The sudden gradient imbalance triggers high
                mitotic drive (Channel 8), causing border cells to divide and regrow the missing anatomy
                until homeostatic balance is restored.
              </p>
            </div>
          </div>
        </div>

        {/* Real-World Significance */}
        <div className="p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] text-xs text-zinc-300 flex flex-col gap-1.5 font-sans">
          <strong className="font-mono text-zinc-100 text-xs uppercase tracking-wider">
            Why Does This Matter?
          </strong>
          <p className="text-zinc-400 text-[11px] leading-relaxed">
            NCA represents a paradigm shift toward <strong className="text-zinc-200">fault-tolerant computing</strong>.
            Applications include self-reconfiguring drone swarms, regenerative soft robotics that walk even
            when severed, synthetic bio-printing, and micro-footprint procedural game asset generation.
          </p>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end pt-2 border-t border-white/[0.08]">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-black font-mono text-xs font-bold transition-all cursor-pointer shadow-[0_0_15px_rgba(16,185,129,0.4)]"
          >
            RETURN TO SIMULATOR
          </button>
        </div>
      </div>
    </div>
  );
};
